version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    image: node:lts-alpine
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://user:password@db:5432/db
    command: "sh -c 'npm install; npm run dev'"

volumes:
  db-data: {}
